### ISSUE TITLE
Changing time resolution of the simulation

### ISSUE THREAD

**Issue by aleks-radw** [utwente-energy/alpg#1]
Hello!
I'm using the tool for the Master Thesis in the TU Eindhoven. I see that you did not fully implement the time rounding feature (to change the simulation resolution) although you started. Some loads (full electricity load, saved in file ElectricityProfile.csv) are in 1 minute resolution already. I was trying to change the time resolution by myself, but it seems I was doing it in the wrong place of the code.
Can you please point me to the exact moment the definition of the time resolution happens? How do you see the integration of the time resolution roundings in all simulations (e.g. clustering the energy demand of the EVs)?

**Comment by GENETX** [comment]
Hi,

The problem is that at the end I found that too much was hardcoded (e.g. the 1440 minutes for a day you find all over the place). Everything is already in minutes though. We resolved it ourselves by resampling the data in our energy management simulator DEMKit. Note that the ALPG itself will not give you power profiles of EV usage. The purpose of the tool is to generate input data (e.g. constraints) for an external energy management simulation tool or optimization methods. This way, it can be used to compare multiple approaches.

DEMKit is also available open-source to academia. Information is published in chapter 6 of my PhD thesis: https://research.utwente.nl/en/publications/a-cyber-physical-systems-perspective-on-decentralized-energy-mana 

If you want more info / get in touch, please e-mail me at g.hoogsteen [at] utwente.nl

Best,
Gerwin Hoogsteen
